---- DISTINCT

SELECT DISTINCT department
FROM products;

SELECT COUNT(DISTINCT department)
FROM products;

-- DISTINCT CAN BE REPLACED BY GROUP BY, BUT NOT THE OTHER WAY AROUND

SELECT DISTINCT department, name
FROM  products;